// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi1ofcIlqIewG9rm75EIMW0D9qpc2-PXw',
    appId: '1:217524825237:web:ca1829745ba782aa3eff9c',
    messagingSenderId: '217524825237',
    projectId: 'studentmaterialdesk',
    authDomain: 'studentmaterialdesk.firebaseapp.com',
    storageBucket: 'studentmaterialdesk.appspot.com',
    measurementId: 'G-7JYFT14TQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqGPC6zGbggr-6M4jI9dpjDJf5RToKVLM',
    appId: '1:217524825237:android:063874f0494878503eff9c',
    messagingSenderId: '217524825237',
    projectId: 'studentmaterialdesk',
    storageBucket: 'studentmaterialdesk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtWXyhbdq2-5eE1fpEVkAO1gUI5MYHxJ4',
    appId: '1:217524825237:ios:41854460a8898ede3eff9c',
    messagingSenderId: '217524825237',
    projectId: 'studentmaterialdesk',
    storageBucket: 'studentmaterialdesk.appspot.com',
    iosBundleId: 'com.example.smd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtWXyhbdq2-5eE1fpEVkAO1gUI5MYHxJ4',
    appId: '1:217524825237:ios:1c6e2990da19699f3eff9c',
    messagingSenderId: '217524825237',
    projectId: 'studentmaterialdesk',
    storageBucket: 'studentmaterialdesk.appspot.com',
    iosBundleId: 'com.example.smd.RunnerTests',
  );
}
